site_name: Simulate Test Cases
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials:
    - Introduction: tutorials/introduction.md
    - Inputs: tutorials/inputs.md
    - outputs: tutorials/outputs.md
    - Usage: tutorials/usage.md
  - Additional Information: additionalInfo.md
markdown_extensions:
  - md_in_html

extra_css:
  - styles/extra.css
