site_name: Multi-Disciplinary Simulation Suite
repo_url: https://github.com/gorodetsky-umich/mdss.git
repo_name: mdss
theme:
  name: material
  logo: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: blue
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: blue


plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          paths: [mdss]
          options:
            heading_level: 2
            show_source: true
            param_headings: false
            show_root_full_path: false
            show_category_heading: true

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Tutorials:
    - Usage: tutorials/usage.md
    - Inputs: tutorials/inputs.md
    - outputs: tutorials/outputs.md
    - Test Cases: tutorials/test_cases.md
  - API Reference: reference/
  #- API Reference: api/api.md To customize the api reference
  - Additional Information: additionalInfo.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

extra_css:
  - assets/extra.css
